import Head from 'next/head'
import Header from '@/components/Header'
import Banner from '@/components/Banner'
const Ved = () => {
  return (
   <> 
   <Head>
        <title>AudioFi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Banner/>

   </>
  )
}

export default Ved